import { GeneratePlanButton } from "@/components/lists/generate-plan-button";
import { getTimelineTemplatePreview } from "@/server/queries/lists";
import { requireWedding } from "@/server/queries/wedding";

export const metadata = { title: "Countdown" };

/**
 * Instantiate the timeline template: preview computed dates against the
 * wedding date, generate (spec 1, section 6). Wedding date isn't set yet as
 * of this build (open question 7 in docs/HANDOFF.md), so this ships the real
 * empty state that decision calls for, not an edge case bolted on later.
 */
export default async function SetupPlanPage() {
  const wedding = await requireWedding();

  if (!wedding.wedding_date) {
    return (
      <div className="mx-auto max-w-2xl space-y-5">
        <h1 className="font-serif text-2xl">The countdown needs a date</h1>
        <p className="text-sm text-muted">
          The 175-task wedding countdown is generated by counting backwards from your wedding date —
          without one, there is nothing to count down to, so there is nothing to preview yet.
        </p>
        <div className="card space-y-2 p-4 text-sm">
          <p className="font-medium">To set it</p>
          <p className="text-muted">
            There isn&rsquo;t a screen for this yet — set{" "}
            <code className="rounded bg-line/50 px-1">weddings.wedding_date</code> directly in the
            Supabase SQL editor:
          </p>
          <pre className="overflow-x-auto rounded bg-ink px-3 py-2 text-xs text-white">
            {`update public.weddings set wedding_date = '2027-06-12' where id = '${wedding.id}';`}
          </pre>
          <p className="text-muted">Then reload this page.</p>
        </div>
      </div>
    );
  }

  const preview = await getTimelineTemplatePreview(wedding.wedding_date);

  if (!preview.templateFound) {
    return (
      <div className="mx-auto max-w-2xl space-y-5">
        <h1 className="font-serif text-2xl">The countdown template isn&rsquo;t loaded yet</h1>
        <p className="text-sm text-muted">
          Run <code className="rounded bg-line/50 px-1">node scripts/seed-templates.mjs</code> against
          this project (needs <code className="rounded bg-line/50 px-1">NEXT_PUBLIC_SUPABASE_URL</code>{" "}
          and <code className="rounded bg-line/50 px-1">SUPABASE_SERVICE_ROLE_KEY</code>), then reload.
        </p>
      </div>
    );
  }

  const overdueCount = preview.items.filter((i) => i.overdue_on_import).length;
  const bySection = groupBySection(preview.items);

  return (
    <div className="max-w-3xl space-y-5">
      <h1 className="font-serif text-2xl">Countdown preview</h1>
      <p className="text-sm text-muted">
        {preview.items.length} tasks computed against {wedding.wedding_date}.
        {overdueCount > 0
          ? ` ${overdueCount} would land before today — they still generate, dated correctly, just flagged as overdue.`
          : ""}
      </p>

      <GeneratePlanButton />

      <div className="card divide-y divide-line">
        {bySection.map(([section, items]) => (
          <div key={section} className="p-4">
            <p className="mb-2 text-xs font-medium uppercase tracking-wide text-muted">{section}</p>
            <ul className="space-y-1 text-sm">
              {items.map((item) => (
                <li key={item.template_key} className="flex items-baseline justify-between gap-3">
                  <span className={item.overdue_on_import ? "text-red-700" : undefined}>{item.title}</span>
                  <span className="shrink-0 text-xs tabular-nums text-muted">
                    {item.due_date}
                    {item.overdue_on_import ? " · overdue" : ""}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
}

function groupBySection(items: Awaited<ReturnType<typeof getTimelineTemplatePreview>>["items"]) {
  const map = new Map<string, typeof items>();
  for (const item of items) {
    const list = map.get(item.section) ?? [];
    list.push(item);
    map.set(item.section, list);
  }
  return [...map.entries()];
}
