-- ===========================================================================
-- 0011: Budget — manual quantity x unit price (part 1: the enum value)
-- ===========================================================================
-- See docs/specs/06.1-budget-quantity-and-task-linking.md, part A. A fifth
-- costing basis for lines priced by a planner-typed count that isn't a
-- guest headcount -- "12 centrepieces @ £25", "3 hire vans @ £180",
-- "40.5 metres of fairy lights @ £1.20/m". Reuses budget_items.unit_price
-- (already shared by every per-unit basis) and adds one new column,
-- `quantity`, as the multiplier instead of a live guest count.
--
-- `0010_budget.sql` is this session's own prior migration and has not been
-- applied to a live project (docs/HANDOFF.md), but this still gets its own
-- file rather than editing 0010 in place -- "one feature, one migration" is
-- this schema's convention regardless of live-application status (0004/0005
-- did the same for spec 1's two decision rounds).
--
-- This file is ONLY the new enum value. Postgres refuses to let a query use
-- an enum value added by `alter type ... add value` until that add has
-- committed (55P04, "unsafe use of new value") -- and both the Supabase SQL
-- editor and the dashboard's migration runner send a whole pasted/uploaded
-- file as one multi-statement query, which Postgres runs as a single
-- implicit transaction. So the column and the views that reference
-- `'manual'` are `0011_budget_manual_quantity_columns.sql` instead, a
-- second file that must be run after this one has committed (`psql -f` per
-- file, as `scripts/verify-migrations.sh` does, doesn't hit this because it
-- sends each statement separately -- that's why this split wasn't caught
-- until it was pasted into the dashboard).
-- ===========================================================================

alter type public.budget_quantity_basis add value if not exists 'manual';
